#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>
#include <driver/spi_master.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define BOOT_BUTTON_GPIO GPIO_NUM_0
#define PWR_BUTTON_GPIO  GPIO_NUM_40
#define PWR_HOLD_GPIO    GPIO_NUM_41
#define BUZZER_GPIO      GPIO_NUM_42

#define I2C_PORT   I2C_NUM_0
#define I2C_SCL_IO GPIO_NUM_10
#define I2C_SDA_IO GPIO_NUM_11

#define DISPLAY_SPI_HOST SPI2_HOST
#define DISPLAY_WIDTH    240
#define DISPLAY_HEIGHT   280
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY  false
#define DISPLAY_INVERT_COLOR true

#define DISPLAY_DC_PIN   GPIO_NUM_4
#define DISPLAY_CS_PIN   GPIO_NUM_5
#define DISPLAY_CLK_PIN  GPIO_NUM_6
#define DISPLAY_MOSI_PIN GPIO_NUM_7
#define DISPLAY_RST_PIN  GPIO_NUM_8
#define DISPLAY_BL_PIN   GPIO_NUM_15
#define DISPLAY_BACKLIGHT_PIN DISPLAY_BL_PIN
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define TOUCH_RST_PIN GPIO_NUM_13
#define TOUCH_INT_PIN GPIO_NUM_14

#define IMU_INT1_PIN GPIO_NUM_38
#define RTC_INT_PIN  GPIO_NUM_39
#define BAT_ADC_PIN  GPIO_NUM_1

#endif  // _BOARD_CONFIG_H_
